In [9]:
!pip install numpy
!pip install sklearn
!pip install sqlalchemy

In [8]:
import numpy as np
np.random.random_sample([3,2])

array([[0.13339771, 0.7827227 ],
       [0.30528711, 0.79016438],
       [0.64521554, 0.2992707 ]])

In [ ]:
z=np.array([[10,20,30,40],[100,200,300,400]])
print(z)
print(z[0]+z[-1])

In [15]:
y=np.array([1,1,0,1]) 
print(z+y) # numpy broadcasting operations


# broadcasting happens of the number of elements are same 

[[ 11  21  30  41]
 [101 201 300 401]]


In [20]:
# matrix multiplication

s=np.array([1,2])
t=np.array([[10,20,30,40],[100,200,300,400]])

print(s.shape)
print(t.shape)

print(np.matmul(s,t))

(2,)
(2, 4)
[210 420 630 840]


In [22]:
# advanced array operations

a4=np.random.random_sample(10)
print(a4)
print(np.min(a4))
print(np.max(a4))
print(np.sum(a4))
print(np.cumsum(a4))
print(np.sqrt(a4))
print(np.log(a4))

[0.39155318 0.83808368 0.68265279 0.39588194 0.95028959 0.66052866
 0.39081657 0.35533514 0.3979043  0.79028237]
0.35533513651490223
0.9502895940089809
5.853328228655263
[0.39155318 1.22963687 1.91228965 2.3081716  3.25846119 3.91898985
 4.30980642 4.66514156 5.06304585 5.85332823]
[0.62574211 0.91546911 0.82622805 0.6291915  0.97482798 0.81272914
 0.62515324 0.59609994 0.63079656 0.88897828]
[-0.93763393 -0.17663732 -0.38176891 -0.92663924 -0.05098851 -0.41471477
 -0.93951695 -1.03469389 -0.92154377 -0.23536496]


In [24]:
a=np.array([1,7,9])
b=np.array([[1,2,9],[5,8,7]])

print(a==b)
print(b>4)

[[ True False  True]
 [False False False]]
[[False False  True]
 [ True  True  True]]


In [25]:
# subset and slicing

c=np.array([[4,5,10],[5,10,15],[7,8,3],[4,6,9],[10,15,20]])
print(c[:,:])

[[ 4  5 10]
 [ 5 10 15]
 [ 7  8  3]
 [ 4  6  9]
 [10 15 20]]


In [33]:
d=np.array([1,2,3,4,5])
print(d[::-1])

e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e[::-1])

[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [35]:
# Advantage of numpy arrays

import time
size_of_vec=100000

t1=time.time()
x=range(size_of_vec)
y=range(size_of_vec)
z_list=[]

for i in range(len(x)):
    z_list.append(x[i]+y[i])
time.time()-t1

range(0, 100000)


0.03579974174499512

In [41]:
t1=time.time()
x=np.arange(size_of_vec)
y=np.arange(size_of_vec)
z_numpy=x+y
time.time()-t1
# numpy is faster than normal array

0.0019931793212890625

In [45]:
z_list==z_numpy

# the output is same but the time taken by the numpy array is less than the normal array

array([ True,  True,  True, ...,  True,  True,  True])

In [51]:
x=np.arange(1,13).reshape(4,3)
print(x)
v=np.array([1,0,1],[2,3,4])
y=x+v
y

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


TypeError: Field elements must be 2- or 3-tuples, got '2'

In [56]:
x=np.array([1,2,3,4,5,6,7],dtype=np.int32)
y=x[::-1]
y

array([7, 6, 5, 4, 3, 2, 1])

In [58]:
y.strides
# strides is the number of bytes it has to move to reach the next element

(-4,)

In [62]:
x=np.zeros((10,10,10),dtype=np.int32)
print(x.strides)
print(x[::2,::3,::4].strides)

(400, 40, 4)
(800, 120, 16)


In [63]:
a=np.arange(6,dtype=np.int8).reshape(3,2)
print(a)
b=a.T
print(b)
b.strides

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


(1, 2)

In [185]:
np.random.seed(1234)
marks=np.random.randint(20,100,size=(4,6)) # 4 students and 6 subjects
print(marks)

print("Minimum marks in each subject : ",marks.min(axis=0))
print("Maximum marks in each subject : ",marks.max(axis=0))
print("Total marks of each student : ",marks.sum(axis=1))

[[67 58 73 96 44 35]
 [69 43 46 50 63 50]
 [46 78 89 93 67 70]
 [96 57 54 58 87 31]]
Minimum marks in each subject :  [46 43 46 50 44 31]
Maximum marks in each subject :  [96 78 89 96 87 70]
Total marks of each student :  [373 321 443 383]


In [188]:
from sklearn import datasets
iris = datasets.load_iris()
X=iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [189]:
print(type(X))

<class 'numpy.ndarray'>


In [190]:
print(np.shape(X))

(150, 4)


In [192]:
Xsub=X[100:141,2:]
Xsub

array([[6. , 2.5],
       [5.1, 1.9],
       [5.9, 2.1],
       [5.6, 1.8],
       [5.8, 2.2],
       [6.6, 2.1],
       [4.5, 1.7],
       [6.3, 1.8],
       [5.8, 1.8],
       [6.1, 2.5],
       [5.1, 2. ],
       [5.3, 1.9],
       [5.5, 2.1],
       [5. , 2. ],
       [5.1, 2.4],
       [5.3, 2.3],
       [5.5, 1.8],
       [6.7, 2.2],
       [6.9, 2.3],
       [5. , 1.5],
       [5.7, 2.3],
       [4.9, 2. ],
       [6.7, 2. ],
       [4.9, 1.8],
       [5.7, 2.1],
       [6. , 1.8],
       [4.8, 1.8],
       [4.9, 1.8],
       [5.6, 2.1],
       [5.8, 1.6],
       [6.1, 1.9],
       [6.4, 2. ],
       [5.6, 2.2],
       [5.1, 1.5],
       [5.6, 1.4],
       [6.1, 2.3],
       [5.6, 2.4],
       [5.5, 1.8],
       [4.8, 1.8],
       [5.4, 2.1],
       [5.6, 2.4]])

In [197]:
print(X.min(axis=0))
print(X.max(axis=0))


[4.3 2.  1.  0.1]
[7.9 4.4 6.9 2.5]


In [202]:
b=np.array([10,11,12,13,14,15,16,17,18,21,22,23],dtype=np.int32)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23])

In [210]:
c1=b.reshape(3,4)
print(c1)
c1=np.append(c1,[[11,12,13,14]],axis=0)
c1

[[10 11 12 13]
 [14 15 16 17]
 [18 21 22 23]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 21, 22, 23],
       [11, 12, 13, 14]])

In [212]:
c2=b.reshape(3,4)
print(c2)
c2=np.append(c2,[[31],[32],[33]],axis=1)
c2

[[10 11 12 13]
 [14 15 16 17]
 [18 21 22 23]]


array([[10, 11, 12, 13, 31],
       [14, 15, 16, 17, 32],
       [18, 21, 22, 23, 33]])

In [215]:
arr1=np.array([[101,102],[103,104]])
print(np.insert(arr1,1,[111,112],axis=0)) # insert at the index 1
np.insert(arr1,1,[111,112],axis=1)

[[101 102]
 [111 112]
 [103 104]]


array([[101, 111, 102],
       [103, 112, 104]])

In [218]:
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]]) # printing the values by index
# or
print(np.array([a[0,0], a[1,1],a[2,0]])) # passing the each element index

[1 4 5]
[1 4 5]


# SQL Alchemy

In [4]:
import sqlite3

In [5]:
conn=sqlite3.connect("products.db")
type(conn)

sqlite3.Connection

In [6]:
cur=conn.cursor()

In [7]:
cur.execute("""
    create table orders(
        _id int primary key,
        customer_id int not null,
        age int,
        status char(10),
        paymentType char(10)
    );
""")

In [9]:
result=cur.execute("SELECT name FROM sqlite_master;")
result.fetchone()

('orders',)

In [14]:
res=cur.execute("SELECT name FROM sqlite_master WHERE name='order_details';")
res.fetchone() is None

True

In [15]:
cur.execute("""
    INSERT INTO orders VALUES 
    (101,2100,34,"paid","CreditCard"),
    (102,2102,25,"checkout","upi-netbanking")
""")

In [16]:
conn.commit

<function Connection.commit>

In [19]:
res=cur.execute("SELECT * FROM orders;")
res.fetchall()

[(101, 2100, 34, 'paid', 'CreditCard'),
 (102, 2102, 25, 'checkout', 'upi-netbanking')]

In [22]:
# insert more data

data=[
    (103,2101,25,"expired","CreditCard"),
    (104,2103,25,"expired","CreditCard"),
    (105,2104,26,"completed","upi-netbanking")
]
cur.executemany("INSERT INTO orders VALUES(?,?,?,?,?)",data)
conn.commit()

IntegrityError: UNIQUE constraint failed: orders._id

In [23]:
res=cur.execute("SELECT * FROM orders;")
res.fetchall()

[(101, 2100, 34, 'paid', 'CreditCard'),
 (102, 2102, 25, 'checkout', 'upi-netbanking'),
 (103, 2101, 25, 'expired', 'CreditCard'),
 (104, 2103, 25, 'expired', 'CreditCard'),
 (105, 2104, 26, 'completed', 'upi-netbanking')]

In [24]:
for row in cur.execute("SELECT age, paymenttype FROM orders ORDER BY age"):
    print(row)

(25, 'upi-netbanking')
(25, 'CreditCard')
(25, 'CreditCard')
(26, 'upi-netbanking')
(34, 'CreditCard')


In [25]:
conn.close()