In [1]:
# 1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, 
# sub-directories to find all duplicates files.
# Delete the found duplicate file.
# [Hint: use hashlib]

import os
import hashlib
#Function to find duplicate files
def findDuplicate(path):
    hashedFilePath = {}
    for root, dirName, files in os.walk(path):
        for file in files:
            filePath = os.path.join(root, file)
            with open(filePath, 'rb') as f:
                fileHash = hashlib.sha256(f.read()).hexdigest()
            if fileHash in hashedFilePath:
                hashedFilePath[fileHash].append(filePath)
            else:
                hashedFilePath[fileHash] = [filePath]
    return {fileHash:filePath for fileHash, filePath in hashedFilePath.items() if len(filePath) > 1}
# path = input("Enter file path: ")
path = str(input("Enter the path of the folders: "))
duplicateFiles = findDuplicate(path)
if len(duplicateFiles) == 0:
    print("No Duplicate Files found!")
else:
    # removal of duplicate files
    for fileHash, filePath in duplicateFiles.items():
        print("Duplicate file hash value is: {}".format(fileHash))
        for file in filePath[:-1]:
            os.remove(file)

Enter the path of the folders: ./folders
No Duplicate Files found!


In [2]:
# 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
# Using these packages [random, strings]

import random
import string
lowercase="abcdefghijklmnopqrstuvwxyz"
uppercase=lowercase.upper()
digits="0123456789"
specials=string.punctuation
password=""
password+=uppercase[random.randint(0,25)]
for _ in range(2):
    password+=lowercase[random.randint(0,25)] 
for _ in range(2):
    password+=digits[random.randint(0,9)] 
password="".join(random.sample(password,len(password)))
password+=specials[random.randint(0,len(specials)-1)]
print(password)

3co0P"


In [3]:
# 3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced 
# by cube of the positioned number.

import numpy as np
def isPrime(x):
    if x < 2:
        return False
    for i in range(2, x):
        if x % i == 0:
            return False
    return True
def primeCubes(matrix,count):
    for i in range(rows):
        for j in range(cols):
            if isPrime(count):
                matrix[i][j]=count**3
            count+=1
    return np.array(matrix)

rows=int(input("Enter number of rows: "))
cols=int(input("Enter number of cols: "))
matrix=[[0 for _ in range(cols)] for _ in range(rows)]
print(primeCubes(matrix,0))

Enter number of rows: 2
Enter number of cols: 3
[[  0   0   8]
 [ 27   0 125]]


In [21]:
# 4.	Python program to get the sum of every cubed value and its previous integer. 

l=[i for i in range(7)]
print(l)
for i in range(len(l)):
    if isPrime(i):
        l[i]=(l[i]**3)+l[i-1]
print(l)

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 9, 36, 4, 129, 6]


In [5]:
# 5.	Given two arrays, find their intersection. Examples:

# Input:  arr1[] = [1, 3, 4, 5, 7]
#         arr2[] = [2, 3, 5, 6]

arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]
intersection=[i for i in arr2 if i in arr1]
intersection

[3, 5]

In [14]:
# 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

array=np.arange(0,49*7,7).reshape(7,7)
array[-1,-1]

336

In [15]:
# 7.	Checker Board Patten using Numpy:
# [   1   0   1   0   1   0   1
#     0   1   0   1   0   1   0
#     1   0   1   0   1   0   1
#     0   1   0   1   0   1   0
#     1   0   1   0   1   0   1  ]


def checker(rows, cols):
    states=np.ones((rows,cols),dtype="int")
    states[1::2,::2],states[::2,1::2]=0,0
    return states
print(checker(int(input("Enter number of rows: ")),int(input("Enter number of cols: "))))

Enter number of rows: 2
Enter number of cols: 3
[[1 0 1]
 [0 1 0]]


In [18]:
# 8.	Create a given Matrix:
# [  A,     B,     C,       D
#    E,      F,     G,       H
#     I,      a,      K,       L
#    M,    N,     o,       P
#    Q,     R,      S,       T
#    U,     0,     W,      O ]

# Replace all the vowels by np.nan
# A, E, I, O U  -- >  np.nan
# Return the count of the missing values


letters=[
    ["A","B","C","D"],
    ["E","F","G","H"],
    ["I","J","K","L"],
    ["M","N","O","P"],
    ["Q","R","S","T"],
    ["U","V","W","X"]
]
vowels="AEIOU"
for list in letters:
    for letter in list:
        if letter in vowels:
            list[list.index(letter)]=np.nan
print(np.array(letters))

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]
