In [1]:
!pip install pytest

In [2]:
# numpy - numerical python
# pandas - data frames

In [3]:
# numpy
# image is a stored in a 3d matrix
# grayscale image is stored in a 2d matrix

In [4]:
# pandas

# Structured
# ---------------------
# Data is arranged in tabular form
# eg. excel, RDBMS, MSAccess

# delimiters => space, comma, semi-colon, tab

# Semi-structured
# ------------------
# json => key-value pair
# XML => .xml
# <rowid>
# <orderid></orderid>
# <productid></productid>
# <price></price>
# <rowid>

# Unstructured
# ------------------
# textfile, pdf, docs, html

# Big Data file formats
# =========================
# These files stores data in compressed format.
# parquet, avro -> Hive

In [5]:
# used for numerical python (alias np)
import numpy as np

In [7]:
print(np.__version__)

1.21.5


#### Numpy Array

In [8]:
list1=[1,2,3,4,5,6,7]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# N-Dimensional array
type(np.array(list1))

numpy.ndarray

In [10]:
arr1=np.array(list1)

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arr1.shape

(7,)

In [13]:
arr1.ndim

1

In [14]:
# returns size in bytes used by entire array
arr1.nbytes

28

#### Array Operations
* Simple array mathematical operations

In [16]:
list1=[10,20,30,40,50,60,70,80,90]
list2=[2,4,3,4,5,6,7,8,9]
list3=[i/j for i, j in zip(list1,list2)]
print(list3)

[5.0, 5.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]


In [17]:
print(np.array(list1)/np.array(list2))

[ 5.  5. 10. 10. 10. 10. 10. 10. 10.]


In [18]:
np.divide(list1,list2)

array([ 5.,  5., 10., 10., 10., 10., 10., 10., 10.])

In [22]:
arr1=np.array([10,20,30,40,50,60,70,80,90])
arr2=np.array([2])
arr1+arr2

array([12, 22, 32, 42, 52, 62, 72, 82, 92])

In [24]:
np.arange(1,11,2)
# generates numpy array using arange(start, stop, stepsize) 


array([1, 3, 5, 7, 9])

In [25]:
np.arange(2, 21, 2)
# numpy array of even numbers 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Types of numpy array

In [39]:
# dtype= data-type with size
# int8, int16, int32, int64
# -128 to 127
arr1=np.array([10,12,15,18,16,20,25,256,255,254,128],dtype="int8")
arr1

array([  10,   12,   15,   18,   16,   20,   25,    0,   -1,   -2, -128],
      dtype=int8)

In [35]:
arr2=np.array([10,12,15,18,16,20,25],dtype="float32")
arr2

array([10., 12., 15., 18., 16., 20., 25.], dtype=float32)

In [40]:
print(list1)
list1.__sizeof__()

[10, 20, 30, 40, 50, 60, 70, 80, 90]


136

In [43]:
print(np.arange(10,91,10))
np.arange(11).nbytes

[10 20 30 40 50 60 70 80 90]


44

### Why numpy is better than, list()

In [72]:
import time
def list_version():
    start=time.time()
    list1=[i for i in range(1,100000)]
    list2=[i for i in range(1,100000)]
    list3=[i+j for i, j in zip(list1,list2)]
    end=time.time()
    print("Total time taken for list version: ",end - start)
#     print(list3)

def numpy_version():
    start=time.time()
    arr1=np.arange(1,100000)
    arr2=np.arange(1,100000)
    arr3=arr1+arr2
    end=time.time()
    print("Total time taken for numpy version: ",end - start)
#     print(arr3)

In [93]:
list_version()
numpy_version()

Total time taken for list version:  0.014183282852172852
Total time taken for numpy version:  0.0


#### Two dimensional array

In [94]:
arr2=np.array([[0,1,2,3,4,5,6,7],
               [10,11,12,13,14,15,16,17]])

In [95]:
# shapearray
arr2.shape

(2, 8)

In [96]:
arr2.shape[0],arr2.shape[1]

(2, 8)

In [97]:
# returns dimension
arr2.ndim

2

In [98]:
# slicing in numpy array
# display first row
arr2[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [99]:
# display single element row
arr2[1,3]

13

In [100]:
arr2[-1][-1]

17

In [101]:
# slicing 2D array
# displays all rows and cols except last row and last col
arr2[:-1,:-1]

array([[0, 1, 2, 3, 4, 5, 6]])

#### Three Domensional array

In [107]:
# 3D Array => Tensor
arr2=np.array([[[0,1,2,3,4,5,6,7],
               [10,11,12,13,14,15,16,17]],
             [[1,1,2,3,4,5,6,7],
               [10,11,12,13,14,15,16,17]],
              [[2,1,2,3,4,5,6,7],
               [10,11,12,13,14,15,16,17]]])
arr2.shape
# rank, rows, cols

(3, 2, 8)

In [108]:
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 1,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 2,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]]])

In [109]:
# shows length of all elements
# size= number of elements present in an array
arr2.size

48

In [114]:
arr2[1,1,4]

14

#### Empty array and fill it with some constant values

In [116]:
arr4=np.empty(6,dtype="int32")
arr4
# these are the buffer values

array([     2,      4,      6, 199994, 199996, 199998])

In [118]:
arr5=np.arange(0,36).reshape(4,9)
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [120]:
arr5=arr5.reshape(3,3,4)
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

#### Reversing an array

In [122]:
arr6=np.arange(50)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [123]:
arr6[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Create and array using Methods
* np.ones()
* np.zeros()

In [124]:
# shape -> 3 rows, 6 cols
np.zeros((3,6),dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

* Identity Matrix
    * Generate a n*n identity matrix, default matrix dtype=float
    * diagonal values are 1, non diagonal values are 0

In [125]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [126]:
np.identity(7,dtype="int")

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [128]:
# start, stop, elements
# equally spaces elements
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [129]:
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 1,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 2,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]]])

In [132]:
arr2[:,:,1:7]

array([[[ 1,  2,  3,  4,  5,  6],
        [11, 12, 13, 14, 15, 16]],

       [[ 1,  2,  3,  4,  5,  6],
        [11, 12, 13, 14, 15, 16]],

       [[ 1,  2,  3,  4,  5,  6],
        [11, 12, 13, 14, 15, 16]]])

In [ ]:
boundary=np.