In [1]:
# create the patterns using numpy

In [2]:
# [
#     1 1 1 1 1
#     1 0 0 0 1
#     1 0 0 0 1
#     1 1 1 1 1
# ]

# [
#     1 0 1 0 1 0
#     0 1 0 1 0 1
#     1 0 1 0 1 0
#     0 1 0 1 0 1
# ]

In [3]:
import numpy as np
def border(rows,cols):
    states=np.zeros((rows,cols),dtype="int")
    states[0]=[1]*cols
    states[1:-1,0],states[1:-1,-1]=1,1
    states[-1]=[1]*cols
    return states

print(border(6,5))

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [4]:
def checker(rows, cols):
    states=np.ones((rows,cols),dtype="int")
    states[1::2,::2],states[::2,1::2]=0,0
    return states
print(checker(6,5))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [5]:
np.nan

nan

In [6]:
states=np.ones((10,10))
states[1::2,::2],states[::2,1::2]=np.nan,np.nan
print(states)

[[ 1. nan  1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1. nan  1.]]


In [7]:
np.isnan(states) # a function which returns a boolean value true for missing data and false for non-missing data

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [8]:
# np.count_nonzero() counts false or 0 values
np.count_nonzero(np.isnan(states))

50

In [37]:
list2=[]
asci=65
for i in range(6):
    list2.append([])
for i in range(6):
    for j in range(4):
        list2[i].append(chr(asci))
        asci+=1
for i in range(6):
    for j in range(4):
        if list2[i][j] in ['A','E','I','O','U']:
            list2[i][j]=0
arr_2=np.array(list2)   
arr_2


for i in range(6):
    for j in range(4):
        if arr_2[i][j] ==0:
            arr_2[i][j]=np.nan



SyntaxError: invalid non-printable character U+00A0 (3178097236.py, line 6)

In [38]:
arr2=np.arange(0,36).reshape(6,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
np.flipud(arr2) # up/down

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [40]:
np.fliplr(arr2) # leftright

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [42]:
np.flip(arr2) # both ud() and lr()

array([[35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

#### Numpy - Array calculation Method

In [43]:
arr3=np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr3.sum() # sum of all elements

21

In [45]:
arr3.sum(axis=0) # sum of corresponding elements of rows

array([5, 7, 9])

In [48]:
arr3.sum(axis=1) # sum of cols

array([ 6, 15])

In [49]:
arr3.min()

1

In [50]:
arr4=[0,0,0,1,0,0,0]
np.argmax(arr4) # returns index of the max value along the axis

3

In [64]:
arr5=np.arange(0,36).reshape(6,6)
# arr5=np.flipud(arr5)
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [65]:
np.argmax(arr5,axis=0)

array([5, 5, 5, 5, 5, 5], dtype=int64)

In [66]:
arr5=np.fliplr(arr5)
arr5

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [67]:
np.argmax(arr5,axis=1)

array([0, 0, 0, 0, 0, 0], dtype=int64)

#### Statistical analysis on an array

In [69]:
arr6=np.arange(6).reshape(2,3)
arr6

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
arr6.mean()

2.5

#### Statistical methods
* Central Tendency
    * Mean
    * Median
    * Mode

In [74]:
np.mean(arr6)

2.5

In [75]:
np.median(arr6)

2.5

In [80]:
np.std(arr6)

1.707825127659933

In [82]:
np.var(arr6)

2.9166666666666665